name: Build Roletopia

on:
  push:
    branches:
      - '**'
  pull_request:

jobs:
  build:
    permissions:
      contents: read
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Restore
        run: dotnet restore Roletopia.sln

      - name: Build
        run: dotnet build Roletopia.sln --configuration Release --no-restore
